### ISSUE TITLE
Sending an invitation without a request object

### ISSUE THREAD

**Issue by mamatmania-iidx** [jazzband/django-invitations#183]
I would like to send an invite after a post_save signal has been triggered. Let's say an admin adds a "Profile" object with an email in it.

This block of code is supposed to send an email to the invitee once it is saved
```
@receiver(post_save, sender=Profile)  
def my_handler(sender, **kwargs):  
    invitation = get_invitation_model()
    invite = invitation.create(sender.email)
    invite.send_invitation(request)
```

This returns an error, because apparently you need to have a request to actually send the invitation.

I wonder if it's possible to send an invitation without a request?

**Comment by valberg** [comment]
This is because the default implementation uses the request to get proper links to render in the email.

You could implement your own by subclassing `AbstractBaseInvitation` (https://github.com/jazzband/django-invitations/blob/09cbae8cfdc04ffc22de42431f16d5986f7344fd/invitations/base_invitation.py#L8) and implement your own `send_invitation` method.
